version: '3.8'

services:
  db:
    image: postgres:15
    container_name: emailservice_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  emailservice:
    build: .
    container_name: emailservice_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5005:5005"

volumes:
  pgdata:
