name: CI Pipeline - Test Checking

on:
  push:
    branches: master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: env
    env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_API_URL: ${{ secrets.MAILGUN_API_URL }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        DOTENV_PATH: "./.env"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permissions to Gradle Wrapper
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle

      - name: Build the Application
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test
