name: CI Pipeline - Test Checking

on:
  push:
    branches: master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle

      - name: Grant execute permissions to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build the Application
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
            name: test-results
            path: build/reports/tests/test/